npm install fs --save
npm install https --save
npm install readline --save
npm install bcrypt --save
npm install body-parser --save
npm install ejs --save
npm install express --save
npm install express-session --save
npm install frappe-gantt --save
npm install method-override --save
npm install moment --save
npm install node-gyp --save 
npm install passport --save
npm install passport-local --save
npm install password-validator --save
npm install role-acl --save
npm install snapsvg --save
npm install sqlite3 --save
npm install unique-string --save
npm install uuid --save
npm install validator --save
npm install yesno --save
