#!/bin/bash
npm install express --save
npm install express-session --save
npm install passport --save
npm install passport-local --save
npm install bcrypt --save
npm install body-parser --save
npm install sqlite3 --save
npm install method-override --save
npm install ejs --save
npm install fs --save
npm install https --save
npm install uuid --save
npm install readline --save
npm install first-run --save
npm install role-acl --save
npm install yesno --save
npm install frappe-gantt --save
npm install snapsvg --save
npm install moment --save
npm install unique-string --save